//! Skill-pack loader + verifier.
//!
//! A *skill pack* is a self-contained `.cvguard-skill.zip`
//! archive that ships the taxonomy / thresholds / severity
//! rubric / lexicons / regex sets / SLM prompt for one
//! deployment scope (global baseline, community overlay,
//! jurisdiction overlay). The archive is signed offline via
//! ed25519 by the CV-Guard signing HSM and verified on-device at
//! load time.
//!
//! This module ports the *base-pack* loader + verifier half of
//! cv-guard's `shared/skillpack/` reference. The overlay loader
//! (community / jurisdiction) and the optional known-hash
//! database (WS6D perceptual-hash gate) live alongside this loader.
//!
//! ### Entry points
//!
//! * [`verify_skill_pack`] — verify a `.cvguard-skill.zip` blob
//!   and return the decoded [`VerificationResult`] (manifest +
//!   extracted file bytes). Does **not** deserialize the YAML
//!   payloads — that step is delegated so a caller can re-use
//!   the verified bytes for hash-pinned distribution caching
//!   without paying the parse cost.
//! * [`verify_skill_pack_with_limit`] — same as above but with a
//!   per-entry uncompressed-size cap. Defense-in-depth for
//!   memory-constrained hosts that want to bound deflate-bomb
//!   exposure on top of the cryptographic signing requirement.
//! * [`load_skill_pack_from_files`] — turn the verified file
//!   bytes into a fully-decoded [`SkillPack`] in memory.
//! * [`load_verified_skill_pack`] — convenience wrapper that
//!   chains both calls. The most common entrypoint for
//!   production hosts.
//!
//! ### Path constants
//!
//! Every constant the compiler emits is re-exported through
//! [`paths`] (and the crate root). Callers introspecting a pack
//! archive directly should pin against these literals.
//!
//! ### Cross-platform invariant
//!
//! Every byte-level fixture in `tests/skillpack_parity.rs` is
//! generated by `tools/gen_skill_pack_fixtures.py`, which imports
//! cv-guard's reference `shared/skillpack/compiler.py` to build
//! and sign the fixture pack. The Rust verifier then replays the
//! signature check against the captured bytes — any silent drift
//! in the digest / signing-preimage / canonical-JSON layer
//! between Python and Rust would fail the parity test
//! immediately. cv-guard itself is **NOT** a CI dependency of
//! this crate; the fixture file is the source of truth and the
//! oracle is developer-side.
//!
//! ### Overlays
//!
//! In addition to the base-pack loader / verifier above, this
//! module ships the *community* and *jurisdiction* overlay
//! merge machinery:
//!
//! * [`overlay_schema`] — closed-shape types
//!   ([`CommunityOverlay`], [`JurisdictionOverlay`],
//!   [`OverlayThresholdEntry`], [`OverlaySeverityLevel`],
//!   [`OverlayLexiconAddition`], [`OverlayRegexAddition`]) plus
//!   the prompt-suffix character allowlist + length cap.
//! * [`overlay`] — [`apply_community_overlay`],
//!   [`apply_jurisdiction_overlay`], [`PROTECTED_CATEGORIES`].
//!   The merge is a pure function of `(base, overlay)`. The
//!   child-safety floor is enforced inside both apply functions.
//! * [`overlay_resolver`] — [`ResolvedPack`],
//!   [`resolve_effective_pack`], [`select_overlays_from_hints`].
//!   Applies overlays in *jurisdiction-then-community* order so a
//!   community preference can never loosen a jurisdiction's legal
//!   requirement.
//!
//! Mirrors cv-guard's `shared/skillpack/overlay_schema.py`,
//! `shared/skillpack/overlay.py`,
//! `shared/skillpack/jurisdiction_overlay.py`, and
//! `shared/skillpack/overlay_resolver.py` one-for-one.

pub mod anti_misuse;
pub mod data;
pub mod error;
pub mod loader;
pub mod overlay;
pub mod overlay_resolver;
pub mod overlay_schema;
pub mod paths;
pub mod revocation;
pub mod schema;
pub mod verifier;

pub use anti_misuse::{
    assert_lexicons_have_provenance, assert_no_invented_categories, assert_no_vague_categories,
    assert_privacy_rules_not_redefined, assert_protected_contexts_for_strict_floors,
    assert_required_signers, pack_kind, validate_or_raise, validate_pack_value, AntiMisuseError,
    AntiMisuseReport, PackKind, PROTECTED_CONTEXT_REQUIRED_SEVERITY, REQUIRED_PROTECTED_CONTEXTS,
};
pub use error::SkillPackError;
pub use loader::{load_skill_pack_from_files, load_verified_skill_pack};
pub use overlay::{apply_community_overlay, apply_jurisdiction_overlay, PROTECTED_CATEGORIES};
pub use overlay_resolver::{resolve_effective_pack, select_overlays_from_hints, ResolvedPack};
pub use overlay_schema::{
    CommunityOverlay, JurisdictionOverlay, OverlayLexiconAddition, OverlayRegexAddition,
    OverlaySeverityLevel, OverlayThresholdEntry, MAX_LEXICON_ADDITIONS_PER_OVERLAY,
    MAX_LEXICON_ADDITION_ENTRIES, MAX_LEXICON_ENTRY_PHRASE_CHARS, MAX_REGEX_ADDITIONS_PER_OVERLAY,
    MAX_SLM_PROMPT_SUFFIX_CHARS,
};
pub use paths::{
    HATE_LEXICON_DIR, KNOWN_HASHES_PATH, REGEX_DIR, RUBRIC_PATH, SCAM_PHRASES_DIR, SLM_PROMPT_PATH,
    TAXONOMY_PATH, THRESHOLDS_PATH,
};
pub use revocation::{
    PassportValidationError, RevocationEntry, RevocationList, Signature as RevocationSignature,
    Verify as RevocationVerify, SIGNATURE_ALGORITHM,
};
pub use schema::{
    Lexicon, LexiconEntry, RegexPattern, RegexSet, SkillPack, SkillPackManifest, TaxonomyConfig,
};
pub use verifier::{
    verify_skill_pack, verify_skill_pack_with_limit, DEFAULT_MAX_UNCOMPRESSED_SIZE, SkillPackSource,
    VerificationResult,
};
